// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package source

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"ackGroundMaxTime": {
			Default:     "",
			Description: "",
			Type:        sdk.ParameterTypeDuration,
			Validations: []sdk.Validation{},
		},
		"ackGroupMaxSize": {
			Default:     "",
			Description: "",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{},
		},
		"name": {
			Default:     "",
			Description: "",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"subscriptionType": {
			Default:     "exclusive",
			Description: "",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"exclusive", "shared", "failover"}},
			},
		},
		"topic": {
			Default:     "",
			Description: "",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"url": {
			Default:     "",
			Description: "",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
	}
}
